### ISSUE TITLE
SlimmerBox should impl Send/Sync where inner types are threads-safely

### ISSUE THREAD

**Issue by richox** [Qqwy/rust-slimmer_box#3]
as what `std::ptr::Unique` does, SlimmerBox should impl these traits like:
```
unsafe impl<T: Send + ?Sized> Send for SlimmerBox<T> {}
unsafe impl<T: Sync + ?Sized> Sync for SlimmerBox<T> {}
```

**Comment by Qqwy** [comment]
Yes, these definitely should exist! Thank you for making this issue! 💚

**Comment by Qqwy** [comment]
Version 0.6.5 has been released which adds these missing trait implementations 👍
